site_name: OnDemand Loop Guide
site_url: https://iqss.github.io/ondemand-loop/
docs_dir: content

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  features:
    - toc.integrate
  custom_dir: overrides
  palette:
    - scheme: default
      primary: '#212529'
      accent: '#a4c6fb'
    - scheme: slate
      primary: '#212529'
      accent: '#a4c6fb'

extra_css:
  - assets/bootstrap.css
  - assets/guide.css

nav:
  - Home: index.md
  - User Guide:
      - Introduction: user_guide/index.md
      - Projects: user_guide/projects.md
      - Finding Data: user_guide/finding_data.md
      - Supported Repositories: user_guide/supported_repositories.md
      - Downloading Files: user_guide/downloading_files.md
      - Uploading Files: user_guide/uploading_files.md
      - Upload File Selector: user_guide/upload_file_selector.md
  - Admin Guide: admin.md
  - Installation Guide: installation.md
  - Development Guide:
      - Overview: development_guide/index.md
      - Architecture and Code: development_guide/architecture.md
      - Connectors: development_guide/connectors.md
      - Local Environment: development_guide/local_environment.md
      - Docker Images: development_guide/docker_images.md
      - Upgrading Open OnDemand: development_guide/upgrade_ood.md
      - Dataverse Integration: development_guide/dataverse_integration.md
      - Contributing a Change: development_guide/contributing.md
      - GitHub Actions: development_guide/github_actions.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
